export const ROSTER_LABELS = [
  "Boo",
  "Contender",
  "Player",
  "Link",
  "Prospect",
  "Babe",
  "Option",
  "Situationship",
];

export const FLAGS = [
  { text: "Great Kisser", emoji: "💋" },
  { text: "Ghoster", emoji: "👻" },
  { text: "Walking Red Flag", emoji: "🚩" },
  { text: "Situationship", emoji: "💫" },
  { text: "Dry Texter", emoji: "🌵" },
  { text: "Main Character Energy", emoji: "✨" },
  { text: "Golden Retriever Energy", emoji: "🐶" },
  { text: "No Cap", emoji: "🧢" },
  { text: "Cap", emoji: "🎭" },
  { text: "Cringe", emoji: "😬" },
  { text: "Delulu", emoji: "🌈" },
  { text: "Lovebomber", emoji: "🎇" },
  { text: "Soft Launch Only", emoji: "🫣" },
  { text: "Hard Launch Ready", emoji: "📸" },
  { text: "Emotionally Unavailable", emoji: "🚪" },
  { text: "Emotionally Available", emoji: "🫶" },
  { text: "Therapy Babe", emoji: "🧠" },
  { text: "Too Online", emoji: "📱" },
  { text: "Bad Vibes", emoji: "💀" },
  { text: "Left On Read", emoji: "👀" },
  { text: "Clingy", emoji: "🪢" },
  { text: "Low Effort", emoji: "😴" },
  { text: "Potential", emoji: "💫" },
  { text: "Confident", emoji: "🍆" },
  { text: "Based", emoji: "💯" },
  { text: "Reply Guy", emoji: "💬" },
  { text: "Certified Lover", emoji: "🎧" },
  { text: "Situationship Veteran", emoji: "🥲" },
  { text: "Side Character Energy", emoji: "🌟" },
  { text: "Independent", emoji: "🦅" },
  { text: "High Maintenance", emoji: "🧼" },
  { text: "Green Texts", emoji: "🤢" },
  { text: "Simp", emoji: "🥺" },
  { text: "Cat Person", emoji: "🐱" },
  { text: "Gym Bro", emoji: "🏋️" },
  { text: "Has a Podcast", emoji: "🎙️" },
  { text: "Mommy Issues", emoji: "🧍‍♂️" },
];

export const RATING_CATEGORIES = [
  {
    id: "vibe",
    label: "Vibe",
    emojis: ["🌵", "😬", "😌", "🫶", "⚡️"],
  },
  {
    id: "humor",
    label: "Humor",
    emojis: ["😴", "😐", "🤔", "😅", "🤣"],
  },
  {
    id: "communication",
    label: "Communication",
    emojis: ["📵", "🫥", "💬", "📖", "🧠"],
  },
  {
    id: "chemistry",
    label: "Chemistry",
    emojis: ["🧊", "😐", "✨", "🔥", "🚀"],
  },
  {
    id: "consistency",
    label: "Consistency",
    emojis: ["🚩", "🤷‍♀️", "✅", "📈", "🔒"],
  },
  {
    id: "hotness",
    label: "Hotness",
    emojis: ["🙈", "😒", "😏", "😉", "🥵"],
  },
  {
    id: "style",
    label: "Style",
    emojis: ["🫠", "🧢", "👟", "🕶️", "💅"],
  },
];

export const HOW_WE_MET_OPTIONS = [
  "Tinder",
  "Bumble",
  "Hinge",
  "BFF",
  "Instagram",
  "Twitter",
  "Mutual Friend",
  "At a Bar",
  "Coffee Shop",
  "Gym",
  "Work",
  "School",
  "Drunken Hookup",
  "Stalked on LinkedIn",
  "Met at a Funeral",
  "In Line at Chipotle",
  "Both Got Ghosted by Same Person",
  "Met at a Protest",
  "In a Discord Server",
  "Both Got Food Poisoning at Same Restaurant",
  "Met at a Wedding (Not Ours)",
  "In a Facebook Group for People Who Hate Facebook Groups",
];
